In [ ]:
# Name : Sayyed Mudassar Iqbal Shakil Ahmed
# Batch : DSG2404
# Subject : Webscrapping 2 Assignment Solution

In [1]:
import pandas as pd
import selenium
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common import exceptions
import time

In [5]:
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import StaleElementReferenceException

In [2]:
#Answer 1:
driver=webdriver.Chrome()

In [3]:
driver.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")

In [37]:
Name=[]
Artist=[]
Upload_Date=[]
Views=[]

In [38]:
nm=driver.find_elements(By.XPATH,"//*[@id='mw-content-text']/div[1]/table[1]/tbody/tr/td[1]")
for i in nm:
    if i.text is None :
        Name.append("--") 
    else:
        Name.append(i.text)
print(len(Name),Name)

30 ['"Baby Shark Dance"[7]', '"Despacito"[10]', '"Johny Johny Yes Papa"[18]', '"Bath Song"[19]', '"See You Again"[20]', '"Shape of You"[25]', '"Wheels on the Bus"[28]', '"Phonics Song with Two Words"[29]', '"Uptown Funk"[30]', '"Gangnam Style"[31]', '"Learning Colors – Colorful Eggs on a Farm"[36]', '"Dame Tu Cosita"[37]', '"Axel F"[38]', '"Masha and the Bear – Recipe for Disaster"[39]', '"Baa Baa Black Sheep"[40]', '"Lakdi Ki Kathi"[41]', '"Sugar"[42]', '"Counting Stars"[43]', '"Roar"[44]', '"Waka Waka (This Time for Africa)"[45]', '"Shree Hanuman Chalisa"[46]', '"Humpty the train on a fruits ride"[47]', '"Sorry"[48]', '"Thinking Out Loud"[49]', '"Perfect"[50]', '"Dark Horse"[51]', '"Let Her Go"[52]', '"Faded"[53]', '"Girls Like You"[54]', '"Lean On"[55]']

In [39]:
Ar=driver.find_elements(By.XPATH,"//*[@id='mw-content-text']/div[1]/table[1]/tbody/tr/td[2]")
for i in Ar:
    if i.text is None :
        Artist.append("--") 
    else:
        Artist.append(i.text)
print(len(Artist),Artist)

30 ["Pinkfong Baby Shark - Kids' Songs & Stories", 'Luis Fonsi', "LooLoo Kids - Nursery Rhymes and Children's Songs", 'Cocomelon - Nursery Rhymes', 'Wiz Khalifa', 'Ed Sheeran', 'Cocomelon - Nursery Rhymes', 'ChuChu TV Nursery Rhymes & Kids Songs', 'Mark Ronson', 'Psy', 'Miroshka TV', 'Ultra Records', 'Crazy Frog', 'Get Movies', 'Cocomelon - Nursery Rhymes', 'Jingle Toons', 'Maroon 5', 'OneRepublic', 'Katy Perry', 'Shakira', 'T-Series Bhakti Sagar', 'Kiddiestv Hindi - Nursery Rhymes & Kids Songs', 'Justin Bieber', 'Ed Sheeran', 'Ed Sheeran', 'Katy Perry', 'Passenger', 'Alan Walker', 'Maroon 5', 'Major Lazer Official']

In [40]:
date=driver.find_elements(By.XPATH,"//*[@id='mw-content-text']/div[1]/table[1]/tbody/tr/td[4]")
for i in date:
    if i.text is None :
        Upload_Date.append("--") 
    else:
        Upload_Date.append(i.text)
print(len(Upload_Date),Upload_Date)

30 ['June 17, 2016', 'January 12, 2017', 'October 8, 2016', 'May 2, 2018', 'April 6, 2015', 'January 30, 2017', 'May 24, 2018', 'March 6, 2014', 'November 19, 2014', 'July 15, 2012', 'February 27, 2018', 'April 5, 2018', 'June 16, 2009', 'January 31, 2012', 'June 25, 2018', 'June 14, 2018', 'January 14, 2015', 'May 31, 2013', 'September 5, 2013', 'June 4, 2010', 'May 10, 2011', 'January 26, 2018', 'October 22, 2015', 'October 7, 2014', 'November 9, 2017', 'February 20, 2014', 'July 25, 2012', 'December 3, 2015', 'May 31, 2018', 'March 22, 2015']

In [41]:
v=driver.find_elements(By.XPATH,"//*[@id='mw-content-text']/div[1]/table[1]/tbody/tr/td[3]")
for i in v:
    if i.text is None :
        Views.append("--") 
    else:
        Views.append(i.text)
print(len(Views),Views)

30 ['14.66', '8.47', '6.92', '6.75', '6.30', '6.28', '6.22', '5.84', '5.25', '5.20', '5.13', '4.68', '4.60', '4.60', '4.10', '4.07', '4.06', '4.03', '4.01', '3.96', '3.90', '3.84', '3.82', '3.78', '3.75', '3.74', '3.68', '3.65', '3.62', '3.62']

In [42]:
Youtube_Video=pd.DataFrame([])

Youtube_Video['Video Title']=Name
Youtube_Video['Artist']=Artist
Youtube_Video['Upload_Date']=Upload_Date
Youtube_Video['Views In Bllion']=Views
Youtube_Video

,Video Title,Artist,Upload_Date,Views In Bllion
0,"""Baby Shark Dance""[7]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",14.66
1,"""Despacito""[10]",Luis Fonsi,"January 12, 2017",8.47
2,"""Johny Johny Yes Papa""[18]",LooLoo Kids - Nursery Rhymes and Children's Songs,"October 8, 2016",6.92
3,"""Bath Song""[19]",Cocomelon - Nursery Rhymes,"May 2, 2018",6.75
4,"""See You Again""[20]",Wiz Khalifa,"April 6, 2015",6.30
5,"""Shape of You""[25]",Ed Sheeran,"January 30, 2017",6.28
6,"""Wheels on the Bus""[28]",Cocomelon - Nursery Rhymes,"May 24, 2018",6.22
7,"""Phonics Song with Two Words""[29]",ChuChu TV Nursery Rhymes & Kids Songs,"March 6, 2014",5.84
8,"""Uptown Funk""[30]",Mark Ronson,"November 19, 2014",5.25
9,"""Gangnam Style""[31]",Psy,"July 15, 2012",5.20
10,"""Learning Colors – Colorful Eggs on a Farm""[36]",Miroshka TV,"February 27, 2018",5.13
11,"""Dame Tu Cosita""[37]",Ultra Records,"April 5, 2018",4.68
12,"""Axel F""[38]",Crazy Frog,"June 16, 2009",4.60
13,"""Masha and the Bear – Recipe for Disaster""[39]",Get Movies,"January 31, 2012",4.60
14,"""Baa Baa Black Sheep""[40]",Cocomelon - Nursery Rhymes,"June 25, 2018",4.10
15,"""Lakdi Ki Kathi""[41]",Jingle Toons,"June 14, 2018",4.07
16,"""Sugar""[42]",Maroon 5,"January 14, 2015",4.06
17,"""Counting Stars""[43]",OneRepublic,"May 31, 2013",4.03
18,"""Roar""[44]",Katy Perry,"September 5, 2013",4.01
19,"""Waka Waka (This Time for Africa)""[45]",Shakira,"June 4, 2010",3.96
20,"""Shree Hanuman Chalisa""[46]",T-Series Bhakti Sagar,"May 10, 2011",3.90
21,"""Humpty the train on a fruits ride""[47]",Kiddiestv Hindi - Nursery Rhymes & Kids Songs,"January 26, 2018",3.84
22,"""Sorry""[48]",Justin Bieber,"October 22, 2015",3.82
23,"""Thinking Out Loud""[49]",Ed Sheeran,"October 7, 2014",3.78
24,"""Perfect""[50]",Ed Sheeran,"November 9, 2017",3.75
25,"""Dark Horse""[51]",Katy Perry,"February 20, 2014",3.74
26,"""Let Her Go""[52]",Passenger,"July 25, 2012",3.68
27,"""Faded""[53]",Alan Walker,"December 3, 2015",3.65
28,"""Girls Like You""[54]",Maroon 5,"May 31, 2018",3.62
29,"""Lean On""[55]",Major Lazer Official,"March 22, 2015",3.62

In [43]:
Youtube_Video.index += 1

In [44]:
Youtube_Video.rename_axis('Rank', axis=0)

,Video Title,Artist,Upload_Date,Views In Bllion
Rank,,,,
1,"""Baby Shark Dance""[7]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",14.66
2,"""Despacito""[10]",Luis Fonsi,"January 12, 2017",8.47
3,"""Johny Johny Yes Papa""[18]",LooLoo Kids - Nursery Rhymes and Children's Songs,"October 8, 2016",6.92
4,"""Bath Song""[19]",Cocomelon - Nursery Rhymes,"May 2, 2018",6.75
5,"""See You Again""[20]",Wiz Khalifa,"April 6, 2015",6.30
6,"""Shape of You""[25]",Ed Sheeran,"January 30, 2017",6.28
7,"""Wheels on the Bus""[28]",Cocomelon - Nursery Rhymes,"May 24, 2018",6.22
8,"""Phonics Song with Two Words""[29]",ChuChu TV Nursery Rhymes & Kids Songs,"March 6, 2014",5.84
9,"""Uptown Funk""[30]",Mark Ronson,"November 19, 2014",5.25
10,"""Gangnam Style""[31]",Psy,"July 15, 2012",5.20
11,"""Learning Colors – Colorful Eggs on a Farm""[36]",Miroshka TV,"February 27, 2018",5.13
12,"""Dame Tu Cosita""[37]",Ultra Records,"April 5, 2018",4.68
13,"""Axel F""[38]",Crazy Frog,"June 16, 2009",4.60
14,"""Masha and the Bear – Recipe for Disaster""[39]",Get Movies,"January 31, 2012",4.60
15,"""Baa Baa Black Sheep""[40]",Cocomelon - Nursery Rhymes,"June 25, 2018",4.10
16,"""Lakdi Ki Kathi""[41]",Jingle Toons,"June 14, 2018",4.07
17,"""Sugar""[42]",Maroon 5,"January 14, 2015",4.06
18,"""Counting Stars""[43]",OneRepublic,"May 31, 2013",4.03
19,"""Roar""[44]",Katy Perry,"September 5, 2013",4.01
20,"""Waka Waka (This Time for Africa)""[45]",Shakira,"June 4, 2010",3.96
21,"""Shree Hanuman Chalisa""[46]",T-Series Bhakti Sagar,"May 10, 2011",3.90
22,"""Humpty the train on a fruits ride""[47]",Kiddiestv Hindi - Nursery Rhymes & Kids Songs,"January 26, 2018",3.84
23,"""Sorry""[48]",Justin Bieber,"October 22, 2015",3.82
24,"""Thinking Out Loud""[49]",Ed Sheeran,"October 7, 2014",3.78
25,"""Perfect""[50]",Ed Sheeran,"November 9, 2017",3.75
26,"""Dark Horse""[51]",Katy Perry,"February 20, 2014",3.74
27,"""Let Her Go""[52]",Passenger,"July 25, 2012",3.68
28,"""Faded""[53]",Alan Walker,"December 3, 2015",3.65
29,"""Girls Like You""[54]",Maroon 5,"May 31, 2018",3.62
30,"""Lean On""[55]",Major Lazer Official,"March 22, 2015",3.62

In [45]:
#Answer 2
driver=webdriver.Chrome()

In [48]:
driver.get("https://www.bcci.tv/")

In [49]:
search=driver.find_element(By.XPATH,'/html/body/header/div[3]/div[2]/ul/div[1]/a[2]')
search.click()

In [52]:
Team=[]
Date_Time =[]
Ground=[]
Test_ODI=[]

In [57]:
tm=driver.find_elements(By.XPATH,'//div[@class="match-card-middle d-flex"]')
for i in tm:
    if i.text is None :
        Team.append("--") 
    else:
        Team.append(i.text)
print(len(Team),Team)

5 ['India (Women)\nSouth Africa (Women)', 'Zimbabwe\nIndia', 'Zimbabwe\nIndia', 'India (Women)\nSouth Africa (Women)', 'India (Women)\nSouth Africa (Women)']

In [59]:
DT=driver.find_elements(By.XPATH,'//div[@class="match-date-info"]')
for i in DT:
    if i.text is None :
        Date_Time.append("--") 
    else:
        Date_Time.append(i.text)
print(len(Date_Time),Date_Time)

5 ['5 Jul\n19:00 IST', '6 Jul\n16:30 IST', '7 Jul\n16:30 IST', '7 Jul\n19:00 IST', '9 Jul\n19:00 IST']

In [60]:
#scraping the Ground 
G=driver.find_elements(By.XPATH,'//div[@class="match-venue ng-scope"]')
for i in G:
    if i.text is None :
        Ground.append("--") 
    else:
        Ground.append(i.text)
print(len(Ground),Ground)

5 ['MA Chidambaram Stadium, Chennai', 'Harare Sports Club, Harare', 'Harare Sports Club, Harare', 'MA Chidambaram Stadium, Chennai', 'MA Chidambaram Stadium, Chennai']

In [61]:
#scraping the Test_ODI 
TO=driver.find_elements(By.XPATH,'//h5[@class="match-tournament-name ng-binding"]')
for i in TO:
    if i.text is None :
        Test_ODI.append("--") 
    else:
        Test_ODI.append(i.text)
print(len(Test_ODI),Test_ODI)

5 ['South Africa Women Tour Of India T20 Series 2024', 'India Tour Of Zimbabwe T20I Series 2024', 'India Tour Of Zimbabwe T20I Series 2024', 'South Africa Women Tour Of India T20 Series 2024', 'South Africa Women Tour Of India T20 Series 2024']

In [65]:
#creating dataframe
International_Fixtures=pd.DataFrame()
International_Fixtures['Team']=Team
International_Fixtures['Date_Time']=Date_Time
International_Fixtures['Series']=Test_ODI
International_Fixtures['Ground']=Ground
International_Fixtures

,Team,Date_Time,Series,Ground
0,India (Women)\nSouth Africa (Women),5 Jul\n19:00 IST,South Africa Women Tour Of India T20 Series 2024,"MA Chidambaram Stadium, Chennai"
1,Zimbabwe\nIndia,6 Jul\n16:30 IST,India Tour Of Zimbabwe T20I Series 2024,"Harare Sports Club, Harare"
2,Zimbabwe\nIndia,7 Jul\n16:30 IST,India Tour Of Zimbabwe T20I Series 2024,"Harare Sports Club, Harare"
3,India (Women)\nSouth Africa (Women),7 Jul\n19:00 IST,South Africa Women Tour Of India T20 Series 2024,"MA Chidambaram Stadium, Chennai"
4,India (Women)\nSouth Africa (Women),9 Jul\n19:00 IST,South Africa Women Tour Of India T20 Series 2024,"MA Chidambaram Stadium, Chennai"

In [68]:
International_Fixtures['Team']=International_Fixtures['Team'].str.replace('\n',' vs ')
International_Fixtures['Date_Time']=International_Fixtures['Date_Time'].str.replace('\n',' ')

In [69]:
International_Fixtures

,Team,Date_Time,Series,Ground,Data_Time
0,India (Women) vs South Africa (Women),5 Jul 19:00 IST,South Africa Women Tour Of India T20 Series 2024,"MA Chidambaram Stadium, Chennai",5 Jul 19:00 IST
1,Zimbabwe vs India,6 Jul 16:30 IST,India Tour Of Zimbabwe T20I Series 2024,"Harare Sports Club, Harare",6 Jul 16:30 IST
2,Zimbabwe vs India,7 Jul 16:30 IST,India Tour Of Zimbabwe T20I Series 2024,"Harare Sports Club, Harare",7 Jul 16:30 IST
3,India (Women) vs South Africa (Women),7 Jul 19:00 IST,South Africa Women Tour Of India T20 Series 2024,"MA Chidambaram Stadium, Chennai",7 Jul 19:00 IST
4,India (Women) vs South Africa (Women),9 Jul 19:00 IST,South Africa Women Tour Of India T20 Series 2024,"MA Chidambaram Stadium, Chennai",9 Jul 19:00 IST

In [84]:
#Answer 3
driver=webdriver.Chrome()

In [85]:
driver.get("http://statisticstimes.com/")

In [86]:
search=driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/button')
search.click()

india=driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]')
india.click()

In [87]:
state=driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
state.click()

In [88]:
Rank=[]
State =[]
GDP=[]
GSDP_Current=[]
GSDP_Previous=[]
Share=[]

In [89]:
#scraping the Rank 
r=driver.find_elements(By.XPATH,'//td[@class="data1"]')
for i in r:
    if i.text is None :
        Rank.append("--") 
    else:
        Rank.append(i.text)
print(len(Rank),Rank)

68 ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '']

In [90]:
#scraping the State 
St=driver.find_elements(By.XPATH,"//td[@class='name']")
for i in St:
    if i.text is None :
        State.append("--") 
    else:
        State.append(i.text)
print(len(State),State)

68 ['Maharashtra', 'Tamil Nadu', 'Karnataka', 'Uttar Pradesh', 'Gujarat', 'West Bengal', 'Rajasthan', 'Andhra Pradesh', 'Telangana', 'Madhya Pradesh', 'Kerala', 'Delhi', 'Haryana', 'Odisha', 'Bihar', 'Punjab', 'Assam', 'Chhattisgarh', 'Jharkhand', 'Uttarakhand', 'Jammu & Kashmir', 'Himachal Pradesh', 'Goa', 'Tripura', 'Chandigarh', 'Puducherry', 'Meghalaya', 'Sikkim', 'Manipur', 'Arunachal Pradesh', 'Nagaland', 'Mizoram', 'Andaman & Nicobar Islands', 'India', 'Maharashtra', 'Tamil Nadu', 'Karnataka', 'Uttar Pradesh', 'Gujarat', 'West Bengal', 'Rajasthan', 'Andhra Pradesh', 'Telangana', 'Madhya Pradesh', 'Kerala', 'Delhi', 'Haryana', 'Bihar', 'Odisha', 'Punjab', 'Assam', 'Chhattisgarh', 'Jharkhand', 'Uttarakhand', 'Jammu & Kashmir', 'Himachal Pradesh', 'Goa', 'Tripura', 'Chandigarh', 'Puducherry', 'Meghalaya', 'Manipur', 'Sikkim', 'Arunachal Pradesh', 'Nagaland', 'Mizoram', 'Andaman & Nicobar Islands', 'India']

In [91]:
#scraping the GDP 
gdp=driver.find_elements(By.XPATH,"//*[@id='table_id']/tbody/tr/td[6]")
for i in gdp:
    if i.text is None :
        GDP.append("--") 
    else:
        GDP.append(i.text)
print(len(GDP),GDP)

33 ['13.17%', '8.78%', '8.38%', '8.37%', '8.17%', '5.63%', '5.06%', '4.87%', '4.76%', '4.63%', '3.96%', '3.73%', '3.68%', '2.81%', '2.76%', '2.62%', '1.74%', '1.74%', '1.52%', '1.13%', '0.82%', '0.73%', '0.36%', '0.27%', '0.20%', '0.19%', '0.16%', '0.16%', '0.16%', '0.15%', '0.13%', '0.12%', '0.04%']

In [92]:
#scraping the Share 
shr=driver.find_elements(By.XPATH,"//*[@id='table_id']/tbody/tr/td[5]")
for i in shr:
    if i.text is None :
        Share.append("--") 
    else:
        Share.append(i.text)
print(len(Share),Share)

33 ['3,108,022', '2,071,286', '1,978,094', '1,975,595', '1,928,683', '1,329,238', '1,193,489', '1,148,471', '1,124,204', '1,092,964', '934,542', '881,336', '868,905', '662,886', '650,302', '617,192', '411,454', '410,525', '358,863', '267,143', '193,352', '172,162', '84,266', '62,550', '46,096', '43,810', '38,785', '37,557', '36,594', '34,775', '31,038', '27,824', '10,371']

In [93]:
#scraping the GSDP_Current 
shr=driver.find_elements(By.XPATH,"//*[@id='table_id']/tbody/tr/td[4]")
for i in shr:
    if i.text is None :
        GSDP_Current.append("--") 
    else:
        GSDP_Current.append(i.text)
print(len(GSDP_Current),GSDP_Current)

33 ['-', '2,364,514', '2,269,995', '2,258,040', '2,230,609', '1,531,758', '1,365,849', '1,303,524', '1,308,034', '1,246,471', '1,046,188', '1,014,688', '984,055', '753,177', '751,396', '676,164', '493,167', '464,399', '393,722', '303,781', '224,226', '191,728', '93,672', '72,636', '54,285', '49,643', '42,697', '42,756', '-', '39,630', '35,643', '-', '-']

In [94]:
#scraping the GSDP_Previous 
shr=driver.find_elements(By.XPATH,"//*[@id='table_id']/tbody/tr/td[8]")
for i in shr:
    if i.text is None :
        GSDP_Previous.append("--") 
    else:
        GSDP_Previous.append(i.text)
print(len(GSDP_Previous),GSDP_Previous)

33 ['-', '1,572,601', '1,423,229', '1,423,358', '-', '904,088', '842,621', '820,894', '767,936', '660,363', '-', '672,247', '634,027', '503,871', '-', '493,283', '318,559', '321,945', '-', '213,378', '139,171', '142,800', '-', '-', '-', '-', '26,524', '-', '-', '-', '-', '-', '-']

In [95]:
State_GDP=pd.DataFrame([])
State_GDP['Rank']=Rank[:33]
State_GDP['State']=State[:33]
State_GDP['Share In GDP']=Share[:33]
State_GDP['GDP of State']=GDP[:33]
State_GDP['GSDP_Current']=GSDP_Current[:33]
State_GDP['GSDP_Previous']=GSDP_Previous[:33]
State_GDP

,Rank,State,Share In GDP,GDP of State,GSDP_Current,GSDP_Previous
0,1,Maharashtra,"3,108,022",13.17%,-,-
1,2,Tamil Nadu,"2,071,286",8.78%,"2,364,514","1,572,601"
2,3,Karnataka,"1,978,094",8.38%,"2,269,995","1,423,229"
3,4,Uttar Pradesh,"1,975,595",8.37%,"2,258,040","1,423,358"
4,5,Gujarat,"1,928,683",8.17%,"2,230,609",-
5,6,West Bengal,"1,329,238",5.63%,"1,531,758","904,088"
6,7,Rajasthan,"1,193,489",5.06%,"1,365,849","842,621"
7,8,Andhra Pradesh,"1,148,471",4.87%,"1,303,524","820,894"
8,9,Telangana,"1,124,204",4.76%,"1,308,034","767,936"
9,10,Madhya Pradesh,"1,092,964",4.63%,"1,246,471","660,363"
10,11,Kerala,"934,542",3.96%,"1,046,188",-
11,12,Delhi,"881,336",3.73%,"1,014,688","672,247"
12,13,Haryana,"868,905",3.68%,"984,055","634,027"
13,14,Odisha,"662,886",2.81%,"753,177","503,871"
14,15,Bihar,"650,302",2.76%,"751,396",-
15,16,Punjab,"617,192",2.62%,"676,164","493,283"
16,17,Assam,"411,454",1.74%,"493,167","318,559"
17,18,Chhattisgarh,"410,525",1.74%,"464,399","321,945"
18,19,Jharkhand,"358,863",1.52%,"393,722",-
19,20,Uttarakhand,"267,143",1.13%,"303,781","213,378"
20,21,Jammu & Kashmir,"193,352",0.82%,"224,226","139,171"
21,22,Himachal Pradesh,"172,162",0.73%,"191,728","142,800"
22,23,Goa,"84,266",0.36%,"93,672",-
23,24,Tripura,"62,550",0.27%,"72,636",-
24,25,Chandigarh,"46,096",0.20%,"54,285",-
25,26,Puducherry,"43,810",0.19%,"49,643",-
26,27,Meghalaya,"38,785",0.16%,"42,697","26,524"
27,28,Sikkim,"37,557",0.16%,"42,756",-
28,29,Manipur,"36,594",0.16%,-,-
29,30,Arunachal Pradesh,"34,775",0.15%,"39,630",-
30,31,Nagaland,"31,038",0.13%,"35,643",-
31,32,Mizoram,"27,824",0.12%,-,-
32,33,Andaman & Nicobar Islands,"10,371",0.04%,-,-

In [109]:
#Answer4
driver=webdriver.Chrome()

In [117]:
driver.get('https://github.com/trending')

In [122]:
Title=[]
Description=[]
Contributers_Count=[]
Language_Used=[]

In [123]:
#scraping the Description
RN=driver.find_elements(By.XPATH,'//p[@class="col-9 color-fg-muted my-1 pr-4"]')
for i in RN:
    if i.text is None :
        Description.append("--") 
    else:
        Description.append(i.text)
print(len(Description),Description)

14 ['18 Lessons, Get Started Building with Generative AI 🔗 https://microsoft.github.io/generative-ai-for-beginners/', 'Python toolkit for quantitative finance', 'Community curated list of templates for the nuclei engine to find security vulnerabilities.', 'The OS for your personal finances', 'The Serenity Operating System 🐞', 'the official Rust and C implementations of the BLAKE3 cryptographic hash function', '🏙 A clean, dark Neovim theme written in Lua, with support for lsp, treesitter and lots of plugins. Includes additional themes for Kitty, Alacritty, iTerm and Fish.', 'A visual no-code/code-free web crawler/spider易采集：一个可视化浏览器自动化测试/数据采集/爬虫软件，可以无代码图形化的设计和执行爬虫任务。别名：ServiceWrapper面向Web应用的智能化服务封装系统。', 'A WhatsApp client library for NodeJS that connects through the WhatsApp Web browser app', '30 days of Python programming challenge is a step-by-step guide to learn the Python programming language in 30 days. This challenge may take more than100 days, follow your own pace. These videos may help too: https://www.youtube.com/channel/UC7PNRuno1rzYPb1xLa4yktw', 'Python - 100天从新手到大师', 'Brand new TTS solution', 'OWASP dependency-check is a software composition analysis utility that detects publicly disclosed vulnerabilities in application dependencies.', 'YDB is an open source Distributed SQL Database that combines high availability and scalability with strong consistency and ACID transactions']

In [124]:
#scraping the Title
RN=driver.find_elements(By.XPATH,'//h2[@class="h3 lh-condensed"]')
for i in RN:
    if i.text is None :
        Title.append("--") 
    else:
        Title.append(i.text)
print(len(Title),Title)

14 ['microsoft / generative-ai-for-beginners', 'goldmansachs / gs-quant', 'projectdiscovery / nuclei-templates', 'maybe-finance / maybe', 'SerenityOS / serenity', 'BLAKE3-team / BLAKE3', 'folke / tokyonight.nvim', 'NaiboWang / EasySpider', 'pedroslopez / whatsapp-web.js', 'Asabeneh / 30-Days-Of-Python', 'jackfrued / Python-100-Days', 'fishaudio / fish-speech', 'jeremylong / DependencyCheck', 'ydb-platform / ydb']

In [125]:
#scraping the Contri Count
RN=driver.find_elements(By.XPATH,'//a[@class="Link Link--muted d-inline-block mr-3"][2]')
for i in RN:
    if i.text is None :
        Contributers_Count.append("--") 
    else:
        Contributers_Count.append(i.text)
print(len(Contributers_Count),Contributers_Count)

14 ['27,831', '747', '2,413', '2,170', '3,136', '316', '369', '3,375', '3,437', '7,154', '51,621', '236', '1,213', '494']

In [126]:
#scraping the Lang_Used
RN=driver.find_elements(By.XPATH,'//span[@class="d-inline-block ml-0 mr-3"]')
for i in RN:
    if i.text is None :
        Language_Used.append("--") 
    else:
        Language_Used.append(i.text)
print(len(Language_Used),Language_Used)

14 ['Jupyter Notebook', 'Jupyter Notebook', 'JavaScript', 'Ruby', 'C++', 'Assembly', 'Lua', 'JavaScript', 'JavaScript', 'Python', 'Python', 'Python', 'Java', 'C++']

In [127]:
Trending_Repository=pd.DataFrame()
Trending_Repository['Name']=Title
Trending_Repository['Description']=Description
Trending_Repository['Language']=Language_Used
Trending_Repository['Conutributers']=Contributers_Count
Trending_Repository

,Name,Description,Language,Conutributers
0,microsoft / generative-ai-for-beginners,"18 Lessons, Get Started Building with Generati...",Jupyter Notebook,"27,831"
1,goldmansachs / gs-quant,Python toolkit for quantitative finance,Jupyter Notebook,747
2,projectdiscovery / nuclei-templates,Community curated list of templates for the nu...,JavaScript,"2,413"
3,maybe-finance / maybe,The OS for your personal finances,Ruby,"2,170"
4,SerenityOS / serenity,The Serenity Operating System 🐞,C++,"3,136"
5,BLAKE3-team / BLAKE3,the official Rust and C implementations of the...,Assembly,316
6,folke / tokyonight.nvim,"🏙 A clean, dark Neovim theme written in Lua, w...",Lua,369
7,NaiboWang / EasySpider,A visual no-code/code-free web crawler/spider易...,JavaScript,"3,375"
8,pedroslopez / whatsapp-web.js,A WhatsApp client library for NodeJS that conn...,JavaScript,"3,437"
9,Asabeneh / 30-Days-Of-Python,30 days of Python programming challenge is a s...,Python,"7,154"
10,jackfrued / Python-100-Days,Python - 100天从新手到大师,Python,"51,621"
11,fishaudio / fish-speech,Brand new TTS solution,Python,236
12,jeremylong / DependencyCheck,OWASP dependency-check is a software compositi...,Java,"1,213"
13,ydb-platform / ydb,YDB is an open source Distributed SQL Database...,C++,494

In [130]:
#Answer 5
driver=webdriver.Chrome()

In [132]:

url='https://www.billboard.com'
driver.get(url)
time.sleep(2)

nav=driver.find_element(By.XPATH,"/html/body/div[3]/header/div[1]/div/div/div[1]/button")
nav.click()

time.sleep(5)

#Hot 100 songs
hot_100=driver.find_element(By.XPATH,'/html[1]/body[1]/div[3]/div[6]/div[1]/div[1]/div[1]/ul[1]/li[1]/ul[1]/li[2]/a[1]')
hot_100.click()

Name=[]
Artist=[]
rank=[]

#Scraping name
Name_tag=driver.find_elements(By.XPATH,"//h3[@class='c-title  a-no-trucate a-font-primary-bold-s u-letter-spacing-0021 u-font-size-23@tablet lrv-u-font-size-16 u-line-height-125 u-line-height-normal@mobile-max a-truncate-ellipsis u-max-width-245 u-max-width-230@tablet-only u-letter-spacing-0028@tablet']")
for i in Name_tag:
    Name.append(i.text)

#Scraping artist
Artist_tag=driver.find_elements(By.XPATH,"//span[@class='c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only u-font-size-20@tablet']")
for i in Artist_tag:
    Artist.append(i.text)

#Scraping rank
rankTag=driver.find_elements(By.XPATH,"//span[@class='c-label  a-font-primary-bold-l a-font-primary-m@mobile-max u-font-weight-normal@mobile-max lrv-u-padding-tb-050@mobile-max u-font-size-32@tablet']")
for i in rankTag[:3]:
    rank.append(i.text )
    
#Scraping name
Rank=[]
nameTag=driver.find_elements(By.XPATH,"//h3[@class='c-title  a-no-trucate a-font-primary-bold-s u-letter-spacing-0021 lrv-u-font-size-18@tablet lrv-u-font-size-16 u-line-height-125 u-line-height-normal@mobile-max a-truncate-ellipsis u-max-width-330 u-max-width-230@tablet-only']")
for i in nameTag:
    Name.append(i.text )

#Scraping artist
artistTag=driver.find_elements(By.XPATH,"//span[@class='c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only']")
for i in artistTag:
    Artist.append(i.text )

#Scraping rank
RankTag=driver.find_elements(By.XPATH,"//span[@class='c-label  a-font-primary-m lrv-u-padding-tb-050@mobile-max']")
for i in RankTag:
    Rank.append(i.text)
    
    
# removing ''
for i in Rank:
    if i=='':
        Rank.remove(i)
        
# slicing Data
last_week_rank=Rank[0::3]
last_week_rank.insert(0,rank[0])
peak_rank=Rank[1::3]
peak_rank.insert(0,rank[1])
weeks_on_board=Rank[2::3]
weeks_on_board.insert(0,rank[2])

driver.close()
# Create Dataframe
songs_top=pd.DataFrame({"Name":Name[:100],"Artist":Artist[:100],"Last Week Rank":last_week_rank[0:100],"Peak Rank":peak_rank[0:100],"Weeks On Board":weeks_on_board[0:100]})
songs_top

In [152]:
#Answer 6

driver=webdriver.Chrome()
driver.maximize_window()
url='https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare'
driver.get(url)

book_name=[]
author_name=[]
volumes_sold=[]
publisher=[]
genre=[]

b_name=driver.find_elements(By.XPATH,'/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr/td[2]')
try:
    for i in b_name:
        book_name.append(i.text)
except:
    book_name.append("-")
    
a_name=driver.find_elements(By.XPATH,'/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr/td[3]')
try:
    for i in a_name:
        author_name.append(i.text)
except:
    author_name.append("-")
    
v_sold=driver.find_elements(By.XPATH,'/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr/td[4]')
try:
    for i in v_sold:
        volumes_sold.append(i.text)
except:
    volumes_sold.append("-")
    
b_publisher=driver.find_elements(By.XPATH,'/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr/td[5]')
try:
    for i in b_publisher:
        publisher.append(i.text)
except:
    publisher.append("-")
    
b_genre=driver.find_elements(By.XPATH,'/html[1]/body[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr/td[6]')
try:
    for i in b_genre:
        genre.append(i.text)
except:
    genre.append("-")
    
driver.close()
Highest_selling_novels=pd.DataFrame({'Book Name':book_name,'Author Name':author_name,'Volumes sold':volumes_sold,'Publisher':publisher,'Genre':genre})
Highest_selling_novels

In [ ]:
#Answer 7
driver=webdriver.Chrome()
driver.maximize_window()
url='https://www.imdb.com/list/ls095964455'
driver.get(url)

name=[]
year=[]
genre=[]
run_time=[]
ratings=[]
votes=[]

s_name=driver.find_elements(By.XPATH,'//h3[@class="lister-item-header"]/a')
try:
    for i in s_name:
        name.append(i.text)
except:
    name.append("--") 
    
s_year=driver.find_elements(By.XPATH,'//h3[@class="lister-item-header"]/span[2]')
try:
    for i in s_year:
        year.append(i.text)
except:
    year.append("--")   

s_genre=driver.find_elements(By.XPATH,'//p[@class="text-muted text-small"]/span[5]')
try:
    for i in s_genre:
        genre.append(i.text)
except:
    genre.append("--")
    
r_time=driver.find_elements(By.XPATH,'//p[@class="text-muted text-small"]/span[3]')
try:
    for i in r_time:
        run_time.append(i.text)
except:
    run_time.append("--")   

rating=driver.find_elements(By.XPATH,'//div[@class="ipl-rating-widget"]/div/span[2]')
try:
    for i in rating:
        ratings.append(i.text)
except:
    ratings.append("--")
    
vote=driver.find_elements(By.XPATH,'//span[@name="nv"]')
try:
    for i in vote:
        votes.append(i.text)
except:
    votes.append("--")
    
driver.close()
tv_series=pd.DataFrame({'Name':name,'Year Span':year,'Genre':genre,'Run Time':run_time,'Ratings':ratings,'Votes':votes})
tv_series

In [ ]:
#Answer 8
driver=webdriver.Chrome()
driver.maximize_window()
url='https://archive.ics.uci.edu/ml/index.php'
driver.get(url)

#clicking on view all Dataset
Dataset= driver.find_elements(By.XPATH,"//span[@class='normal']/b/a")[0].get_attribute('href')
driver.get(Dataset)

# Scraping dataset
data=[]
try:
    data_tag=driver.find_elements(By.XPATH,"//td//p[@class='normal']")
    for i in data_tag[8:4362]:
        data.append(i.text )
except:
    data.append('-')
    
#slicing dataset
Dataset_name=data[::7]
Data_type=data[1::7]
Task=data[2::7]
Attribute_type=data[3::7]
instances=data[4::7]
attribute=data[5::7]
Year=data[6::7]

driver.close()
#creating Dataframe
Datasets= pd.DataFrame({"Dataset name":Dataset_name,"Data type":Data_type,"Task":Task,"Attribute type":Attribute_type,"Instances":instances,"Attribute":attribute,"Year":Year})
Datasets